### ISSUE TITLE
Joke CRD is not generated

### ISSUE THREAD

**Issue by saberkan** [quarkiverse/quarkus-operator-sdk#107]
When building the sample project 

`$ mvn package`

Only JR CRD is generated, Joke CRD is missing : 

`$ ll target/kubernetes/
total 12
-rw-rw-r--. 1 saberkan saberkan 1586 Sep  1 16:59 jokerequests.samples.javaoperatorsdk.io-v1.yml
-rw-rw-r--. 1 saberkan saberkan 4006 Sep  1 16:59 kubernetes.json
-rw-rw-r--. 1 saberkan saberkan 3102 Sep  1 16:59 kubernetes.yml
`

# Additional information

`$ mvn -version
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /usr/local/bin/apache-maven-3.6.3
Java version: 11.0.11, vendor: Red Hat, Inc., runtime: /usr/lib/jvm/java-11-openjdk-11.0.11.0.9-2.el8_4.x86_64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.18.0-305.7.1.el8_4.x86_64", arch: "amd64", family: "unix"

$ java -version
openjdk version "11.0.11" 2021-04-20 LTS
OpenJDK Runtime Environment 18.9 (build 11.0.11+9-LTS)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.11+9-LTS, mixed mode, sharing)
`

**Comment by metacosm** [comment]
This is actually expected. The extension currently only generates CRDs for CustomResources that are associated with a Controller. See #90.
