### ISSUE TITLE
Re-oganize sample folder to allow other projects

### ISSUE THREAD

**Issue by saberkan** [quarkiverse/quarkus-operator-sdk#113]
Currently, there is only one single project (Joke) under samples folder (quarkus-operator-sdk/samples/). 

Is it possible to move the project under (quarkus-operator-sdk/samples/Joke)  ? So other samples can be added in the same folder ?

I've initiated another sample : https://github.com/saberkan/JAVA_HTTPD_OPERATOR, and would like to pull request it ?

Thank you,

**Comment by metacosm** [comment]
It might be a good idea, though I'm a little worried about maintenance of these samples.

**Comment by scrocquesel** [comment]
For me, to keep maintenance low, it should be the same sample as from JOSDK. But, there isn't much work to do to port reconciler code to quarkus. 

What's more difficult it to port tests part to quarkus dev experience. And Joke sample has no test to follow as a guidance.

**Comment by metacosm** [comment]
This is done.
