### ISSUE TITLE
Investigate dev mode improvements

### ISSUE THREAD

**Issue by metacosm** [quarkiverse/quarkus-operator-sdk#12]
It would be nice if we could restart the app when the custom resource classes are changed: the CRD generation would be re-triggered and possibly re-applied on the cluster automatically so that the user can iterate faster on their code as right now this requires stopping the app, generating the CRD, applying it manually and restarting the operator.

**Comment by maxandersen** [comment]
see https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/how.20does.20extensions.20control.2Ftrigger.20reload.20.3F

https://github.com/quarkusio/quarkus/blob/main/extensions/kafka-streams/runtime/src/main/java/io/quarkus/kafka/streams/runtime/devmode/KafkaStreamsHotReplacementSetup.java

**Comment by metacosm** [comment]
A good part of this feature has been implemented in #80.
