### ISSUE TITLE
Error creating cluster role binding after updating to 2.0.0

### ISSUE THREAD

**Issue by lordpengwin** [quarkiverse/quarkus-operator-sdk#148]
I just updated to 2.0.0 and that was the only change that I made, now when i do a `kubectl -f target/kubernetes/kubenetes.yml` I get the following errors:
`Error from server (Invalid): error when creating "target/kubernetes/kubernetes.yml": ClusterRoleBinding.rbac.authorization.k8s.io "appserverrequestcontroller-cluster-role-binding" is invalid: subjects[0].namespace: Required value
Error from server (Invalid): error when creating "target/kubernetes/kubernetes.yml": ClusterRoleBinding.rbac.authorization.k8s.io "testplancoordinator-cluster-role-binding" is invalid: subjects[0].namespace: Required value
Error from server (Invalid): error when creating "target/kubernetes/kubernetes.yml": ClusterRoleBinding.rbac.authorization.k8s.io "testrunnercontroller-cluster-role-binding" is invalid: subjects[0].namespace: Required value`

If i edit the kubernetes.yml file directly and add `namespace:default` to the subject of the cluster role bindings it works fine.
Is this a known issue or am I missing a setting or property somewhere. 
My controllers are annotated with `@Controller(namespaces = Controller.WATCH_CURRENT_NAMESPACE)`

**Comment by metacosm** [comment]
This sounds like a bug. Thank you for reporting it.

**Comment by metacosm** [comment]
This should be addressed by #150 if you can give it a try.
