### ISSUE TITLE
Misleading warning about ClusterRoleBinding 

### ISSUE THREAD

**Issue by metacosm** [quarkiverse/quarkus-operator-sdk#154]
See java-operator-sdk/java-operator-sdk#686 for details.

**Comment by metacosm** [comment]
The problem here is that, currently, the `namespaces` property is only processed at runtime. We therefore need to process them at build time so that we can use **some** information from it to generate the RBACs. The **some** part is important because there are several cases where the needed information is simply not available at build time because it is not known.

The two problematic cases are:
1. a controller that is configured to watch all namespaces needs a `ClusterRoleBinding` to bind the `ClusterRole` to its service account. However, the namespace in which the controller is deployed needs to be provided in the binding.
2. any configuration that require variable interpolation. If values are not provided for all variables the build will fail. However, the values not known at that time (otherwise, we wouldn't need to interpolate them, after all) which means that "fake" values have to be provided which is sub-optimal or even dangerous unless a clear marker value is used so that substitution after build can easily be done.

As of now, we will implement build time handling of the `namespaces` property with the understanding that some cases will fail. We recommend that people requiring variable substitution use the `QUARKUS_JOSDK_PLACEHOLDER` value as a placeholder. If this value is used, the extension will automatically replace it by an empty value which will cause the generated to fail when trying to apply it at runtime. Would that make sense @lburgazzoli?

**Comment by lburgazzoli** [comment]
LGTM

**Comment by metacosm** [comment]
> As of now, we will implement build time handling of the `namespaces` property with the understanding that some cases will fail. We recommend that people requiring variable substitution use the `QUARKUS_JOSDK_PLACEHOLDER` value as a placeholder. If this value is used, the extension will automatically replace it by an empty value which will cause the generated to fail when trying to apply it at runtime. We will also implement a toggle to completely disable RBAC generation from the extension.

Note that this solution is still being evaluated for possible other options.
