### ISSUE TITLE
Operator stuck at startup when using Micrometer @Timed annotation

### ISSUE THREAD

**Issue by jeratora** [quarkiverse/quarkus-operator-sdk#16]
Hello.

When a method of the controller is annotated with @io.micrometer.core.annotation.Timed (createOrUpdateResource for example), the operator remains stuck after being launched using `mvn quarkus:dev.`

>INFO  [io.jav.qua.ext.dep.QuarkusExtensionProcessor] (build-4) Processed 'com.fruit.controller.EntitlementController' controller named 'entitlement' for 'entitlements.owf-oda.tech.fruit' CR (version 'owf-oda.tech.fruit/v1alpha1')

>INFO  [io.quarkus] (Quarkus Main Thread) entitlement-operator 1.0.0-SNAPSHOT on JVM (powered by Quarkus 1.12.1.Final) started in 8.496s. Listening on: http://localhost:8080

>INFO  [io.quarkus] (Quarkus Main Thread) Profile dev activated. Live Coding activated.

>INFO  [io.quarkus] (Quarkus Main Thread) Installed features: [cache, cdi, jaeger, kubernetes, kubernetes-client, micrometer, mutiny, oda-security, operator-sdk, rest-client, resteasy, resteasy-jackson, security, smallrye-context-propagation, smallrye-health, smallrye-jwt, smallrye-openapi, smallrye-opentracing, swagger-ui, vertx, vertx-web]

>WARN  [io.jav.ope.Operator] (Quarkus Main Thread) Skipping registration of com.fruit.controller.EntitlementController_ClientProxy controller named entitlementcontroller_clientproxy because its configuration cannot be found.

>Known controllers are: [entitlement]

>INFO  [com.ora.QuarkusOperator] (Quarkus Main Thread) Starting up Operator

The WARN line and the freeze don't occur without the @Timed annotation.

Environment : 

- Debian 10.8
- OpenJDK 64-Bit Server VM GraalVM CE 21.0.0.2
- Quarkus : 1.12.1.Final
- Java Operator SDK : 1.7.3

Thanks in advance for your help.

**Comment by metacosm** [comment]
Can you add a `name` field to your controller annotation to see if this addresses the issue, please?

**Comment by jeratora** [comment]
> Can you add a `name` field to your controller annotation to see if this addresses the issue, please?

Unfortunately, it was already the case.

`@Controller(name = EntitlementController.CONTROLLER_NAME)`
`public class EntitlementController implements ResourceController<Entitlement> {`

**Comment by metacosm** [comment]
Thanks for trying! 😄 
Looking into it now.
