### ISSUE TITLE
Namespace / all namespace configured via ConfigProperty

### ISSUE THREAD

**Issue by speedfl** [quarkiverse/quarkus-operator-sdk#163]
Hello! 

First thanks a lot for your work. 

Currently the namespace list on which the controller needs to Watch is defined statically in the @controller annotation.
No namespace specified means all Namespaces.
It could be nice to make this configurable.

We could imagine an annotation:

```
@Controller("name")
```

Then on the config properties:

```
quarkus.kubernetes.operator.controller.[name].namespaces=...
```

This will help adding new features

Thanks in advance

Geoffrey

**Comment by metacosm** [comment]
This is actually already implemented… 😉 
The property to use is `quarkus.operator-sdk.controllers.[name].namespaces`. All the values that can be set from the `Controller` annotation are available as properties.

**Comment by speedfl** [comment]
Wow so nice!!! Thanks a lot @metacosm !

Have a good day!
