### ISSUE TITLE
csv generator support

### ISSUE THREAD

**Issue by shawkins** [quarkiverse/quarkus-operator-sdk#217]
If multiple kuberntes.yml files were available to process, or a single kubernetes.yml file contained multiple deployments, it seems like the existing logic would put together the expected csv - but there's an expectation of a single set of resources:

https://github.com/quarkiverse/quarkus-operator-sdk/blob/7a25bca77006b713eac22a687a99654e5c75c524/csv-generator/deployment/src/main/java/io/quarkiverse/operatorsdk/csv/deployment/CSVProcessor.java#L77

Each one of those should extract a list.

Other issues:
- is a template csv file supported?
- can ConfigMaps/Secrets in the kubernetes.yml be copied as their own files in the manifests?

**Comment by metacosm** [comment]
Would it be possible to provide me with an example file that you'd like the extension to process?

**Comment by metacosm** [comment]
I believe this is fixed, please re-open if I'm mistaken.
