### ISSUE TITLE
Add support for -Dquickly

### ISSUE THREAD

**Issue by scrocquesel** [quarkiverse/quarkus-operator-sdk#224]
Samples and it tests, only need other modules to be build and install.

To continue work on https://github.com/quarkiverse/quarkus-operator-sdk/pull/106/files, we may align with Quarkus contribution guide. See https://github.com/quarkusio/quarkus/blob/main/CONTRIBUTING.md#building-main

I tried adding the profile 

```
<profile>
    <id>quick-build</id>
    <activation>
        <property>
            <name>quickly</name>
        </property>
    </activation>
    <properties>
        <skipTests>true</skipTests>
        <skipITs>true</skipITs>
        <skipDocs>true</skipDocs>
    </properties>
    <build>
        <defaultGoal>clean install</defaultGoal>
    </build>
</profile>
```

It does skip some module install and quarkus plugin build, but it still do some maven compile on projects that should be skipped. Need to investigate how it behaves with Quarkus repo.

**Comment by metacosm** [comment]
I don't think it's possible to skip building the integration tests because the code in in `src/main/java` and basically, it means that the extension needs to process them to be able to produce proper maven artifacts.
