### ISSUE TITLE
`finalizers` should be added to resources to generated `ClusterRole` when appropriate

### ISSUE THREAD

**Issue by metacosm** [quarkiverse/quarkus-operator-sdk#301]
/cc @andreaTP

**Comment by andreaTP** [comment]
Unfortunately, the commit doesn't fix the issue for the Keycloak project, we are setting all of the controllers to not use Finalizers:
https://github.com/keycloak/keycloak/blob/f11573eeb26f5a3c47374d9f01a2f6616b7ca82b/operator/src/main/java/org/keycloak/operator/v2alpha1/KeycloakController.java#L51
https://github.com/keycloak/keycloak/blob/f11573eeb26f5a3c47374d9f01a2f6616b7ca82b/operator/src/main/java/org/keycloak/operator/v2alpha1/KeycloakRealmImportController.java#L51

But the exception is still being thrown in OpenShift.
cc. @vmuzikar
