### ISSUE TITLE
[regression?] The operator "generated" main is spuriously starting during Unit tests

### ISSUE THREAD

**Issue by andreaTP** [quarkiverse/quarkus-operator-sdk#304]
I'm not sure if this is a regression or a behavior that was already there and just showed up after the check of the CRD presence on startup.

This is happening:
  - start (pure) unit tests (they don't need to have the operator running at all)
  - an operator is started in background
  - the operator in background creates the CRDs if they are not present in the cluster
  - if the CRDs are taking a little time or you don't have any cluster connected the tests are failing because the background operator crashes
  
## How to reproduce:
in the `operator` sub-module in this PR branch: https://github.com/keycloak/keycloak/pull/11174
  
Run the command:
```
mvn clean verify -Dtest=PodTemplateTest
```

## Issues

- the operator should not start in background during tests and integration tests
- the operator should not automatically create the CRDs

**Comment by metacosm** [comment]
By the way, as a workaround, there's a property that prevents the main from starting during tests but I agree that this should be done in a better way: `-Dquarkus.operator-sdk.start-operator=false`.

**Comment by metacosm** [comment]
Also, why is the `PodTemplateTest` marked as a `QuarkusTest` if it's a simple unit test (as it seems to be?).

**Comment by andreaTP** [comment]
To use `-Dquarkus.operator-sdk.start-operator=false` I should probably split the `verify` goal in two separate runs since in integration tests we are actually running the operator, correct?

**Comment by metacosm** [comment]
The easiest solution would be to not use `QuarkusTest` in tests that are not integration tests. Quarkus wouldn't be bootstrapped and you shouldn't have an issue in that case.

**Comment by metacosm** [comment]
Actually, would it make sense to not start the operator automatically during tests? You could force that behavior using the `quarkus.operator-sdk.start-operator` property, of course. In essence, this would invert the current behavior for tests where the operator is always started and you have to explicitly tell it not to start.

**Comment by metacosm** [comment]
Fixed by https://github.com/quarkiverse/quarkus-operator-sdk/commit/56bcc7b867b3c8963b8d58eb394c0df58bca6424
