### ISSUE TITLE
Operator SDK with Quarkus 2.8.0

### ISSUE THREAD

**Issue by mswiderski** [quarkiverse/quarkus-operator-sdk#310]
Are there any plans to have any time soon a new version that is compatible with quarkus 2.8.0.Final?

Currently upgrading with latest `3.0.7` and there is library (decorate) mismatch that fails at build time with following error:

````
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:2.8.0.Final:build (default) on project mysql-operator: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR] 	[error]: Build step io.quarkus.kubernetes.deployment.KubernetesProcessor#build threw an exception: java.lang.NoSuchMethodError: 'io.fabric8.kubernetes.api.model.ObjectMeta io.quarkiverse.operatorsdk.deployment.AddRoleBindingsDecorator.getMandatoryDeploymentMetadata(io.fabric8.kubernetes.api.model.KubernetesListBuilder)'
[ERROR] 	at io.quarkiverse.operatorsdk.deployment.AddRoleBindingsDecorator.visit(AddRoleBindingsDecorator.java:37)
[ERROR] 	at io.quarkiverse.operatorsdk.deployment.AddRoleBindingsDecorator.visit(AddRoleBindingsDecorator.java:19)
[ERROR] 	at io.fabric8.kubernetes.api.builder.BaseFluent.acceptInternal(BaseFluent.java:96)
[ERROR] 	at io.fabric8.kubernetes.api.builder.BaseFluent.accept(BaseFluent.java:75)
[ERROR] 	at io.dekorate.ResourceRegistry.lambda$generate$3(ResourceRegistry.java:179)
[ERROR] 	at java.base/java.util.HashMap.forEach(HashMap.java:1336)
[ERROR] 	at io.dekorate.ResourceRegistry.generate(ResourceRegistry.java:173)
[ERROR] 	at io.dekorate.Session.generate(Session.java:285)
[ERROR] 	at io.dekorate.Session.close(Session.java:248)
[ERROR] 	at io.quarkus.kubernetes.deployment.KubernetesProcessor.lambda$build$2(KubernetesProcessor.java:173)
[ERROR] 	at java.base/java.util.Optional.ifPresent(Optional.java:183)
[ERROR] 	at io.quarkus.kubernetes.deployment.KubernetesProcessor.build(KubernetesProcessor.java:126)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[ERROR] 	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:925)
[ERROR] 	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
[ERROR] 	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
[ERROR] 	at java.base/java.lang.Thread.run(Thread.java:829)
[ERROR] 	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
````

Looks like decorate 2.8.1 that is used by 3.0.7 has changed in 2.9.0 that is used by quarkus 2.8.0 - method signature has been changed - added new parameter.

**Comment by metacosm** [comment]
Yes, 2.8.0 is not currently compatible with this extension. Compatibility with 2.8+ will probably be reserved to version 4.0.0 of the extension, which should be released soon.

**Comment by mswiderski** [comment]
thanks for quick response @metacosm. Do you mind to keep this issue open until 4.0.0 is out? That will ket me know when to move my stuff to 2.8.x of quarkus and operator sdk.

**Comment by metacosm** [comment]
On second thought, this might have to wait some more because it's not possible to support 2.7 and 2.8 (well, not easily, that is) at the same time and I want 4.0.0 to still be compatible with 2.7.

**Comment by mswiderski** [comment]
by "some more" you mean like a week or two or more a month(s)?

**Comment by metacosm** [comment]
How important is 2.8 support for you? We're working on a solution that might address the issue :)

**Comment by mswiderski** [comment]
I'd say quite important as it brings support for GraalVM 22 and few other parts I'm in need. Though time frame for it from my end is beginning of May, that's why I asked if it's days or weeks away :)

Great to hear about the potential solution. Feel free to let me know as I can try it out on my end as well (if needed of course)

**Comment by metacosm** [comment]
This should be fixed with Quarkus 2.8.1, which as far as I'm aware should be released fairly soon.

**Comment by mswiderski** [comment]
excellent news! will this be 3.0.x or 4.x version of operator sdk?

**Comment by metacosm** [comment]
It should work with both but, moving forward, most work will happen for version 4.

**Comment by mswiderski** [comment]
closing this issue as moving quarkus to 2.8.1 resolves the issue.
