### ISSUE TITLE
Bundle generator tests are failing during release

### ISSUE THREAD

**Issue by metacosm** [quarkiverse/quarkus-operator-sdk#320]
See https://github.com/quarkiverse/quarkus-operator-sdk/runs/6029123899?check_suite_focus=true#step:7:1191

**Comment by Sgitario** [comment]
Having modules (the bundle deployment) that depend on others (the operator sdk bom) which are released at the same time, seem to not be supported by the `@QuarkusProdModeTest` test utility as it tries to build the application model using an unreleased (yet) version of the operator sdk bom. 
We could either 
a. skip the tests when performing the release (which is what Quarkus does - then Quarkus runs the tests using the generated local Maven repository); 
b. or not use  `@QuarkusProdModeTest` as the rest in Quarkiverse, and try to cover these scenarios in the integration tests (which are being ignored when performing the release already btw)

I think the proper way to "fix" this is to not run the tests as we are not running the integration tests modules either. 
Let me know your thoughts about this.

**Comment by Sgitario** [comment]
> I think it's fine to not test during the release. Presumably, tests have all passed before we get to the release anyway.

+100 https://github.com/quarkiverse/quarkus-operator-sdk/pull/321
