### ISSUE TITLE
Question: is it possible to add dependant resources programatically, instead of using annotations?

### ISSUE THREAD

**Issue by juangon** [quarkiverse/quarkus-operator-sdk#342]
Hi!

I am implementing an operator, and depending on the spec, operator should install some other CRD's, but the number is not known until receiving the CR.
I couldn't see anything like this programatically (it is possible through @Dependent annotation in the Reconciler though.

Thanks very much!

**Comment by csviri** [comment]
Do I understand correctly that dependending on the contents of a CR (Custom Resource) you want to install CRD's (Custom Resource Definitions) ?  
This is not possible in the current version of managed dependent resources. (Will be in the followup interations). But basically this dynamic nature does not fit that much into concept. But you can do it either with standalone dependent resources. Or just manully implementing the logic. Somthing like this:

```java

private KubernetesClient client;

@Override
  public UpdateControl<MyResource> reconcile(MyResource resource, Context<MyResource> context)
      throws Exception {
    
if (resource.getSpec().crdIdsToInstall().contain("myCrdId1"))
   client.kubernetesClient.apiextensions().v1().customResourceDefinitions().create(myCrd1())
}

if (resource.getSpec().crdIdsToInstall().contain("myCrdId2"))
   client.kubernetesClient.apiextensions().v1().customResourceDefinitions().create(myCrd2())
}

```

Of course you might optimize it to not install if already installed -  check standalone dependent resource, and how those can help with that (from framework version 3.0 (now RC)): https://javaoperatorsdk.io/docs/dependent-resources#standalone-dependent-resources

**Comment by csviri** [comment]
Hi, not sure I understand what you want to achieve.  Do you want to reconcile when the managed CRD is changed, or?

Pls see also glossary about dependent resource vs secondary resource: https://javaoperatorsdk.io/docs/glossary

**Comment by csviri** [comment]
welcome, pls let us know, if something is not clear, maybe how to improve it more in the docs. thx!

**Comment by juangon** [comment]
Thanks to your support! I have to debug and check how dependent and events go to the primary reconcile.

**Comment by juangon** [comment]
Hi again @csviri ! Is it possible to have a KubernetesDependentResource that is a CustomResource at the same time? I would like to have the possibility of creating a custom resource without using the "parent root" custom resource I have.

**Comment by csviri** [comment]
Hi @juangon , not sure if I understand the question correctly, but you can use custom resources as the resources managed by the KubernetesDependentResource. So for example, you could have your own custom resource instead of Deployment here:
https://github.com/java-operator-sdk/java-operator-sdk/blob/80195c9e905954b277ed376f7385e667fa4c8a12/sample-operators/webpage/src/main/java/io/javaoperatorsdk/operator/sample/DeploymentDependentResource.java

**Comment by juangon** [comment]
Oh ok, sorry for the stupid question :-D. I am sorry, have another one: is it  dr.setLabelSelector (https://github.com/java-operator-sdk/java-operator-sdk/blob/d804ee17c503f99bfea3a3ee5a6f9fe6d0dd7f01/sample-operators/webpage/src/main/java/io/javaoperatorsdk/operator/sample/WebPageStandaloneDependentsReconciler.java#L88) adding a label to those dependent resources so the Reconciler then can check if those dependent are available or not?

**Comment by csviri** [comment]
It's basically just filtering, so only relevant resources are considered.

To explicitly check if resource exists, use "getSecondaryResource", it returns an Optional. if that empty it does not exists.
https://github.com/java-operator-sdk/java-operator-sdk/blob/80195c9e905954b277ed376f7385e667fa4c8a12/operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/ResourceOwner.java#L25-L25

But the `reconcile` method checks this in background.

Note that there is now an update (more might be come before the release) for that:
https://github.com/java-operator-sdk/java-operator-sdk/pull/1217

**Comment by juangon** [comment]
Ok thanks a lot!! Could I create programatically dependent resources in initContext method instead of constructor like this example? https://github.com/java-operator-sdk/java-operator-sdk/blob/main/sample-operators/webpage/src/main/java/io/javaoperatorsdk/operator/sample/WebPageStandaloneDependentsReconciler.java#L79-L90 . I won't know which dependent resources will be until checking the root CustomResource (webPage in this case).

**Comment by csviri** [comment]
That is basically not what you want, event if you might want to have different dependent resource created for a custom resource than for an other, the event source are global and the possible dependent resources are known upfront. So you want to defined all the dependent resources upfront, but you might not want to reconcile all of the for a custom resource instance.(however might be for an other instance).

**Comment by juangon** [comment]
Ok so in order to choose which one I have to reconcile them or not, but have to define all the possible dependants in advance. I think I got it. Thanks again :-)

**Comment by juangon** [comment]
BTW @csviri can I use the code before this fix https://github.com/java-operator-sdk/java-operator-sdk/pull/1217/files ? So, the code existing before that works fine, or should I wait until the new version with that fix?

**Comment by csviri** [comment]
Yes, its basically just fix in usage, not in the implementation itself in the framework.
