### ISSUE TITLE
Primary resource doesn't get secondary resource status update

### ISSUE THREAD

**Issue by juangon** [quarkiverse/quarkus-operator-sdk#349]
Hi! I have a primary resource and "n" number of secondary dependant resources (so, it seems I am using the "standalone" approach.

In fact, project is heavily based on the WebPageStandaloneReconciler.

When adding primary CR, it gets created fine, and in primary reconciler "reconcile" method is executed for secondary resource. That kicks in the secondary resource reconciler,, and as I've seen, the secondary resource status is properly updated and can access it when doing "kubectl describe" in the CR.

The problem is, primary CR doesn't get the updated resource (somehow the reconciler isn't invoked again so it can't check if the secondary resource status has changed or not).

Can you give me a clue of what could be happening? I can attach snippets of source code if needed.

Thanks!

**Comment by csviri** [comment]
Hi @juangon,

the bulk creation of secondary resources is not supported now out of the box, see related issue:
https://github.com/java-operator-sdk/java-operator-sdk/issues/1182

I plan to implement it in the coming weeks. Without the code it is hard to tell what is going wrong. Note that it is not a trivial problem if you haven `n` resource already created but then you reduce this number to for example `n-2` then 2 resources needs to be deleted. There needs to be a way how to identify those two.
Not sure if dependent resource is the best approach for this ATM. An alternative would be to do it without that.

Is your operator open source? can you link it here?

**Comment by juangon** [comment]
Thanks @csviri , I've sent you an email.

**Comment by juangon** [comment]
Ok so in order to make this working I had to do:

1-Add a labelSelector in the "parent" reconciler.
2-In parent reconciler, mplement ' prepareEventSources' with code like this:
``` 
 InformerEventSource<Child, Parent> childEventSrc = new InformerEventSource<>(
            InformerConfiguration.from(Child.class, context)
            .withLabelSelector("app.kubernetes.io/managed-by=parent-controller")
            .build(),
        context);

        childResource.configureWith(teisServiceNowEventSrc);

        EventSource[] sources = Arrays.asList(childResource).stream().map((connector) -> connector.initEventSource(context)).collect(Collectors.toList()).toArray(new EventSource[0]);


        return EventSourceInitializer.nameEventSources(sources);
```
3-In parent reconciler, configure all child resources in parent reconciler like this:
```
       this.childResource = new ChildDependent();

        Arrays.asList(childResource).forEach(dr -> {
          dr.setKubernetesClient(client);
          dr.configureWith(new KubernetesDependentResourceConfig()
              .setLabelSelector("app.kubernetes.io/managed-by=parent-controller"));
        });
```
4.In Child CRUKubernetesDependentResource , add the required label selector in `desired` method:
```
 public Child desired(Parent parent, Context<Parent> context) {       
        
        Map<String, String> labels = new HashMap<>();
        labels.put("app.kubernetes.io/managed-by", "parent-controller");
```
