### ISSUE TITLE
Override Retry configuration for Unit Tests

### ISSUE THREAD

**Issue by manstis** [quarkiverse/quarkus-operator-sdk#380]
We have a `Reconciler` implementing `ErrorStatusHandler`. It uses `DefaultRetryConfiguration` by default.

We have a Unit Test for this `Reconciler` annotated to run within Quarkus's Open Shift Test Server. `@QuarkusTest @WithOpenShiftTestServer`. The Unit Test invokes the `Reconciler` by creating a suitable resource that the `Reconciler` handles: `kubernetesClient.resources(X.class).createOrReplace(expected)`.

We'd like to test the `ErrorStatusHandler` side of things by making our `Reconciler` throw an exception and let the retry mechanism enter our `ErrorStatusHandler`. We can then make assertions based on the operation of the `ErrorStatusHandler` logic.

It is not possible to override `DefaultRetryConfiguration` retry configuration just for the test.

The jist of the code is:

**Reconciler**
```
@Inject
MyService service;

@Override
public UpdateControl<X> reconcile(X x, Context context) {
  service.doSomething();
}

@Override
public Optional<X> updateErrorStatus(X x, RetryInfo retryInfo, RuntimeException e) {
  if (retryInfo.isLastAttempt()) {
    service.error();
  }
}
```
**Test**
```
@QuarkusTest
@WithOpenShiftTestServer
public class XTest {

@Inject
KubernetesClient client;

@InjectMock
MyService service;

@Test
public void test() {
  when(service.doSomething()).thenThrow(new NullPointerException());

  client.resources(X.class).createOrReplace(expected);

  // wait a bit

  verify(service).error();

}
```
We'd like to override the retry so that the `Reconciler` can effectively fail fast.

**Comment by scrocquesel** [comment]
Hello,

you should be able to deactivate retry and so immediately it the last attempt when an error occured in the properties.

`````
%test.quarkus.operator-sdk.controllers."`yourreconciler".retry.max-attempts=0
````

**Comment by manstis** [comment]
Hi @scrocquesel that _sort of_ works....

`ReconciliationDispatcher.handleErrorStatusHandler(...)` is returning a `RetryInfo` with:
```
@Override
public boolean isLastAttempt() {
  return controller.getConfiguration().getRetryConfiguration() == null;
}
```
`controller.getConfiguration().getRetryConfiguration()` is returning `PlainRetryConfiguration` with `max=0` (from `application.properties). However since the call in `isLastAttempt()` checks if the retry configuration is `null` and not that the `count==max` the check for the last attempt is failing. Is the check only for `null` correct or should it also be checking `count==max`? I don't know _how_ this mechanism works.. it might well be that after the penultimate attempt the retry info is meant to be set to `null` somewhere.

**Comment by manstis** [comment]
See [here](https://github.com/java-operator-sdk/java-operator-sdk/blob/main/operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/ReconciliationDispatcher.java#L173-L183) although we're stuck on `2.1.3` due to the version of `quarkus-operator-sdk` we use.
```
[INFO] +- io.quarkiverse.operatorsdk:quarkus-operator-sdk:jar:3.0.6:compile
[INFO] |  +- io.quarkiverse.operatorsdk:quarkus-operator-sdk-common:jar:3.0.6:compile
[INFO] |  |  +- org.jboss:jandex:jar:2.4.2.Final:compile
[INFO] |  |  \- org.jboss.logging:jboss-logging:jar:3.4.3.Final:compile
[INFO] |  +- io.quarkus:quarkus-arc:jar:2.7.5.Final:compile
[INFO] |  |  \- org.eclipse.microprofile.context-propagation:microprofile-context-propagation-api:jar:1.2:compile
[INFO] |  +- io.javaoperatorsdk:operator-framework-core:jar:2.1.3:compile
```

**Comment by scrocquesel** [comment]
Did test with max-attempts=1, and it works but you will got two attempts.

> it might well be that after the penultimate attempt the retry info is meant to be set to `null` somewhere.

Actually, it's the contrary, the retry info is set on the context (and cached for subsequent attempt) after the first try. So the first attempt seems always to be attemptCount = 0, lastAttempt = false.
@csviri , I guess it's a bug. I can't find unit test in JOSDK with max attempt set to zero and testing for last attempt in error handler to confirm the expected behavior.

**Comment by manstis** [comment]
Thank-you @scrocquesel.

I can confirm that works and the general mechanism to override controller configuration seems to solve my issue.

Closing.
