### ISSUE TITLE
Generated bundle should include all CRDs when quarkus.operator-sdk.crd.generate-all=true

### ISSUE THREAD

**Issue by derlin** [quarkiverse/quarkus-operator-sdk#401]
Following #90, I expect the CSV generated by quarkus-operator-sdk-bundle-generator to honour the new property `quarkus.operator-sdk.crd.generate-all`. That is, when the latter is true, the CSV should include all CRDs, even the ones that are not directly managed by a reconciler (in my case, the other CR is used as a dependent resource).

**Comment by metacosm** [comment]
Good point. However, first analysis reveals that it might not be that easy to implement, in particular to figure out how to assign which CRDs to a given reconciler… (should be doable via the dependent annotations, if they are used).

**Comment by derlin** [comment]
Or maybe adding a new annotation targeting the bundle ?
The reconciler may use custom informers and "manual" dependent resources that won't appear in the `@Dependent` annotation at the top.

**Comment by metacosm** [comment]
Please take a look at #412 to see if that fits your needs.
