### ISSUE TITLE
This extension, `kubernetes-client`, `java-generator` and `sundrio` versions: Oh my!

### ISSUE THREAD

**Issue by andreaTP** [quarkiverse/quarkus-operator-sdk#403]
Trying to use the Quarkus Operator SDK together with the `kubernetes-client` `java-generator` easily ends up with compile time issues on the `sundrio` shared dependency.

Rationale:
This extension uses a specific version of `sundrio` at compile time.
Using `sundrio` in the same compilation unit requires the user to align the version of the library with the original one from the extension.

E.g.:
here: https://github.com/andreaTP/bink8s/blob/0177a66e4b31225c0b5a91e5694e80a3d3127df4/pom.xml#L21
I'm forced to use the version of `sundrio` from `kubernetes-client` `5.12`, despite the java-generator only ships and tests with `6.X`.

The errors are pretty obscure as you can imagine (missing methods and similar).
Should `sundrio` be used as a shaded dependency in this project?

**Comment by metacosm** [comment]
How would you go about doing it, though? I don't have a lot of experience with shaded dependencies but have been bitten by them before so I would like to have a clearer idea of what changes would help and how…

**Comment by metacosm** [comment]
@andreaTP do you still think this should be addressed? The dependencies seem to be more or less in control now…

**Comment by andreaTP** [comment]
Some time ago I added `sundrio` to the fabric8 client extended BOM, I think we can close this now.
Thanks for checking on me!
