### ISSUE TITLE
Delay registration unti event is not working in native mode

### ISSUE THREAD

**Issue by mswiderski** [quarkiverse/quarkus-operator-sdk#405]
When building a project with operator sdk extension in native mode then following warning is logged:

````
WARN  [io.qua.config] Unrecognized configuration key "quarkus.operator-sdk.delay-registration-until-event" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
````

and I can confirm that this delay is not respected. While running in jvm mode it does work as expected.

This property is defined in `application.properties`

````
quarkus.operator-sdk.delay-registration-until-event=io.quarkus.runtime.StartupEvent
````

the intention is to only process events by controller when application is fully started and initialised.

Version in use:
Operator SDK extension:4.0.1 (commit: 0a2f95e on branch: 0a2f95e4e591da2f562d7be0ee2039c6f83f3b47) built on Tue Sep 13 19:35:36 GMT 2022
Quarkus: 2.12.2.Final
GraalVM: '22.2.0 Java 17 CE'
Java version: '17.0.4+8-jvmci-22.2-b06'

**Comment by metacosm** [comment]
This functionality has been removed in more recent versions of the Quarkus extension. Note that `StartupEvent` is automatically sent by Quarkus when the app starts so waiting for that event shouldn't make any difference. Could you please detail your use case and why you need this functionality?

**Comment by mswiderski** [comment]
the issue manifest when controller is started after several resources have been registered in the cluster. That sometimes starts to process these resources before the controller (quarkus app) is fully started. So it runs into problems like the beans are not yet registered or still initialising. And that causes the processing to fail or retry.

So what I would like to achieve is the controllers are not processing (or are not yet connected to the api server) until the app fully started. I thought that using the delay until event was the way to go. If that is no longer a feature what would be a good way to do that?

**Comment by metacosm** [comment]
Do you have some code I could look at to reproduce the issue? Normally, the operator shouldn't be started before the `StartupEvent` is issued.

**Comment by metacosm** [comment]
You could deactivate automatic start of the operator and manually start it when your other beans are ready?

**Comment by mswiderski** [comment]
yes, that would work too though I think I will go the way with priorities. I think then we can close this issue as the main response was that the `delay-registration-until-event` feature was removed.

**Comment by metacosm** [comment]
> > You could deactivate automatic start of the operator and manually start it when your other beans are ready?
> 
> just so I know, how do you disable automatic start of the operator?

Set `quarkus.operator-sdk.start-operator` to `false` in `application.properties`.

**Comment by mswiderski** [comment]
yeah, it's quite useful to gain more control about startup procedure.

**Comment by metacosm** [comment]
So reading some more about priorities, it looks like, at least semantically, we should put the operator start up priority within the `LIBRARY_AFTER` and `PLATFORM_AFTER` range (if my understanding of what "late" interceptors are supposed to be).  Would that work for you? I opened #410 for this.

**Comment by mswiderski** [comment]
yes, that would certainly work, thanks a lot
