### ISSUE TITLE
Consider removal of dependency `quarkus-container-image-jib`

### ISSUE THREAD

**Issue by MikeEdgar** [quarkiverse/quarkus-operator-sdk#418]
The artifact `quarkus-operator-sdk` currently has a compile-time dependency on `io.quarkus:quarkus-container-image-jib`. Is this necessary or could it at most be marked optional?

**Comment by metacosm** [comment]
I've been thinking about trimming dependencies, yes. The initial idea was to have a "batteries-included, opinionated" extension but that might be causing more issues than really helping :)
Do you have a particular issue with jib being there at compile-time?

**Comment by MikeEdgar** [comment]
> Do you have a particular issue with jib being there at compile-time?

No technical issue. It's mostly dealing with limiting dependencies on our side as well. Before adding an exclude in our POM, I figured started here first :-)
