### ISSUE TITLE
question: how to configure the operator for leader election ?

### ISSUE THREAD

**Issue by derlin** [quarkiverse/quarkus-operator-sdk#426]
The JOSDK now supports leader election. This is achieved by configuring the `Operator`, as shown here: https://github.com/java-operator-sdk/java-operator-sdk/blob/8865302ac0346ee31f2d7b348997ec2913d5922b/sample-operators/leader-election/src/main/java/io/javaoperatorsdk/operator/sample/LeaderElectionTestOperator.java#L21-L23

Since in quarkus-operator-sdk the `Operator` is created and configured for us, how can we achieve this ?

**Comment by metacosm** [comment]
4.0.2 added the ability to automatically inject `LeaderElectionConfiguration` (and `InformerStoppedHandler`, though that's irrelevant here) beans into the `ConfigurationService`. You just need to provide a CDI bean implementing the interface and it should be properly injected.

**Comment by derlin** [comment]
Thank you ! 
For those interested, I was able to configure the leader election by adding this class to the project:
```java
import io.javaoperatorsdk.operator.api.config.LeaderElectionConfiguration;
import io.quarkus.arc.Unremovable;
import javax.enterprise.context.ApplicationScoped;

@ApplicationScoped
@Unremovable // This is necessary to keep the bean, even if it seems unused (see https://quarkus.io/blog/unused-beans/)
public class EnableLeaderElection extends LeaderElectionConfiguration {
  public EnableLeaderElection() {
    super("<APP_NAME>", "<KUBE_NAMESPACE");
  }  
}
```
