### ISSUE TITLE
Application doesn't start when having more than 10 controllers annotated with @ControllerConfiguration

### ISSUE THREAD

**Issue by juangon** [quarkiverse/quarkus-operator-sdk#440]
When adding more than 10 controller/reconciler annotated with @ControllerConfiguration, application doesn't finish its startup, causing its restart as liveness and readiness checks aren't available.
Quarkus operator versión: 4.0.5

**Comment by juangon** [comment]
> Is there a stack trace you could share? Have you tried running your operator in dev mode to see what happens?

Stack trace added above. Didn't try dev mode, can I create an image in dev profile so I can deploy in my Kubernetes cluster?

**Comment by metacosm** [comment]
You can run your operator locally without having to deploy to your Kubernetes cluster: the only thing you need is to have your `~/.kube/config` file point to the appropriate cluster (by, for example, connecting to it via `kubectl` first).

**Comment by metacosm** [comment]
I don't see anything in the stack trace that would indicate what's going on… :(
Can you activate debug-level logging, please?

**Comment by metacosm** [comment]
Will give it a try.

**Comment by metacosm** [comment]
Actually, the integration tests have more than 10 reconcilers (though some of them are supposed to be ignored) and they work fine.

**Comment by juangon** [comment]
In my case all of them are working with @DependentResource annotations with heavy workflow usage. Can you contact me in private so I can send you the source code?

**Comment by metacosm** [comment]
> @metacosm in my case all of them are working with @DependentResource annotations with heavy workflow usage. Can you contact me in private so I can send you the source code?

Sure.

**Comment by juangon** [comment]
I've seen some magical numbers with "10", like the reconciliation thread number. This one can be modified thrugh this extension, but increasing it seems not working. I've seen there is another one about concurrent workflow executor threads, which has the same default number: https://github.com/java-operator-sdk/java-operator-sdk/blob/main/operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/ConfigurationService.java#L87.

After recompiling both the JOSDK and Quarkus operator SDK, it seems to not work. Any ideas?

**Comment by metacosm** [comment]
Maybe your workflow is creating a deadlock?

**Comment by juangon** [comment]
How would that be possible at application startup?

**Comment by metacosm** [comment]
Yes, there is some sort of deadlock. Looking into it.

**Comment by juangon** [comment]
Thanks @metacosm , if I can help or you need more info just let me know

**Comment by metacosm** [comment]
Maybe we should expose this configuration to users?

**Comment by csviri** [comment]
> Maybe we should expose this configuration to users?

yep, that would be good to have. If I understand correctly this won't be an issue with other http client implementations, just with okHttp

**Comment by manusa** [comment]
> Maybe we should expose this configuration to users?

Given the nature of the applications using this framework (strong informer/watcher/websocket usage), I think it would be reasonable that the SDK provided initial bigger defaults.

Also, moving away from OkHTTP into Jetty or the JDK client should be a priority once you upgrade the dependency to 6.x.

**Comment by juangon** [comment]
> it seems that the issue is with the request limit of the client, when created a client and with higher request limit, the issue is does not appear anymore:
> 
> ```
> @Singleton
>     public KubernetesClient client() {
>         var client = new DefaultKubernetesClient(new ConfigBuilder()
>                 .withMaxConcurrentRequests(1000)
>                 .build());
>         return client;
>     }
> ```
> 
> big thanks to @shawkins and @manusa for help with this.

Thanks very much guys! Now the startup finishes as it should. Closing the issue then
