### ISSUE TITLE
Consider upgrading JOSDK to 4.1.1 to address issues with multiple secondary resources

### ISSUE THREAD

**Issue by jmuis** [quarkiverse/quarkus-operator-sdk#442]
Hi, 

Due to issue https://github.com/java-operator-sdk/java-operator-sdk/issues/1175 deployments fail with multiple resources e.g. when multiple secondary service resources are required.
According to the ticket this should be addressed in release 4.1.0 of the JOSDK (which has been superseded by now with version 4.1.1). 

Could you please consider upgrading the JOSDK to 4.1.1 for release 5.0.0?
I can't overview the overall impact as my knowledge on quarkus/JOSDK is not significant enough atm, otherwise I would just have created a pull request, but again, can't oversee the general impact.

Thanks!

**Comment by metacosm** [comment]
That's the goal but upgrades are not trivial. Currently working on it.

**Comment by metacosm** [comment]
See for example: https://github.com/quarkiverse/quarkus-operator-sdk/pull/441

**Comment by jmuis** [comment]
Ah, right... didn't see that in the issue list. 
Anything I can do?

**Comment by metacosm** [comment]
5.0.0.Beta2 which targets JOSDK 4.1.1 has been released. Let me know if this addresses your issue.

**Comment by jmuis** [comment]
Hi, 

Seems to work just fine! Errors related to multiple secondary resources are gone. 
Thanks for the effort!
