### ISSUE TITLE
Multiple CRD Apply does not work Dev Services Kubernetes 

### ISSUE THREAD

**Issue by csviri** [quarkiverse/quarkus-operator-sdk#455]
If there is an additional custom resource (not just the primary), and using  Dev Services Kubernetes for testing the other CRD's are not applied.

see error  in Joke sample on this PR: 
https://github.com/quarkiverse/quarkus-operator-sdk/pull/454

**Comment by csviri** [comment]
Tbh honest not sure if this should work in this setup (would be nice though), but in this case the extension is being kinda built during the start of the test - that time it tries to apply the CRD (in that time both CRD apply fails), the  primary CRD is actually applied later.

**Comment by csviri** [comment]
reverted joke changes at the, but after this issue is fixed we might change it again:
https://github.com/quarkiverse/quarkus-operator-sdk/pull/454/commits/81d12c3cf4dd19b758784f19374ba8433a2b3a41

**Comment by scrocquesel** [comment]
> Tbh honest not sure if this should work in this setup (would be nice though), but in this case the extension is being kinda built during the start of the test - that time it tries to apply the CRD (in that time both CRD apply fails), the primary CRD is actually applied later.

It should because dev services also serve for dev mode and it should be cool to have CRD reapplied automatically during developpement.
