### ISSUE TITLE
Can't create or push image to container registry in quarkus-operator-sdk 5.0.0

### ISSUE THREAD

**Issue by juangon** [quarkiverse/quarkus-operator-sdk#463]
When trying to build and push container to Container Registry like this:

`./mvnw clean package -Dquarkus.container-image.build=true -Dquarkus.container-image.push=true`

it doesn't  create and push the image.

It was working fine in 5.0.0.Beta2

**Comment by juangon** [comment]
Ok, so it seems JIB was removed in https://github.com/quarkiverse/quarkus-operator-sdk/issues/418, so I just added that dependency.

Thanks!

**Comment by metacosm** [comment]
Ah yes, sorry. I really need to add better documentation… :(
