### ISSUE TITLE
max-retries is ignored in the controller configuration (operator-sdk version 4.0.5 and quarkus 2.13.6)

### ISSUE THREAD

**Issue by r00ta** [quarkiverse/quarkus-operator-sdk#467]
With the operator-sdk version 4.0.5 and quarkus 2.13.6, with the following controller 

```java

@ApplicationScoped
@ControllerConfiguration(name = FooController.NAME, labelSelector = "app.kubernetes.io/managed-by=foocontroller")
public class FooController implements Reconciler<Foo>,
                                      EventSourceInitializer<Foo>,
                                      ErrorStatusHandler<Foo> {

    public static final String NAME = "foocontroller";
    private static final Logger LOGGER = LoggerFactory.getLogger(FooController.class);

    @Override
    public UpdateControl<Foo> reconcile(Foo foo, Context<Foo> context) {
        LOGGER.info("Create or update Foo: '{}' in namespace '{}'",
                    foo.getMetadata().getName(),
                    foo.getMetadata().getNamespace());

        throw new RuntimeException("NICE TRY");
    }

```

and the following `application.properties`
```text
# Looks like this is ignored by quarkus...
quarkus.operator-sdk.controllers.foocontroller.retry.max-attempts=1
```

the reconcile loop is called 5 times instead of just one (when the exception is raised).

See https://github.com/r00ta/issues-reproducers/tree/main/operator-sdk-bug-ignore-max-retries for the reproducer

**Comment by metacosm** [comment]
This is weird because there are tests that check that the values coming from `application.properties` are indeed taken into account. I suspect, though, that, since this configuration has been deprecated in JOSDK for a while, maybe there's something funky going on with the conversion to the supported configuration…

**Comment by metacosm** [comment]
OK, I have found the issue and it's indeed an interplay between the old configuration and the new configuration style and it's rather annoying to fix…  😭

**Comment by metacosm** [comment]
I've opened #469 to address this issue. Could you give it a try and let me know how it goes, please?

**Comment by r00ta** [comment]
Just tested with my reproducer: looks like it works properly with this fix :+1: Thank you!
