### ISSUE TITLE
Expectations for KubernetesClient

### ISSUE THREAD

**Issue by shawkins** [quarkiverse/quarkus-operator-sdk#48]
Since the operator sdk now depends on quarkus-kubernetes-client are we forced to use the openshift client or is there a mechanism to still use the DefaultKubernetesClient?

I'm asking due to https://github.com/fabric8io/kubernetes-client/issues/3179

**Comment by metacosm** [comment]
Right now there isn't but my view on this is that we should address the underlying concern with the client.

**Comment by metacosm** [comment]
I'm assuming this is addressed, please re-open with additional details if needed.
