### ISSUE TITLE
Check Quarkus provided fabric8 version

### ISSUE THREAD

**Issue by andreaTP** [quarkiverse/quarkus-operator-sdk#484]
Given that everything has been merged upstream we should be able to perform this last remaining check:
https://github.com/quarkiverse/quarkus-operator-sdk/blob/c2c17dd01b562984f6bfb5eead70d8f576374a73/core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/OperatorSDKProcessor.java#L159-L160

**Comment by metacosm** [comment]
This won't be available for consumption before 2.17, I think, though…

**Comment by andreaTP** [comment]
possible, opened the issue to avoid forgetting about 🙂
