### ISSUE TITLE
Allow to inject specific KubernetesClient bean

### ISSUE THREAD

**Issue by AleksanderBrzozowski** [quarkiverse/quarkus-operator-sdk#544]
Context: I want to test that operator has proper cluster roles / roles applied. In order to do that, I want to create new service account for test purposes, bind specific roles to the service account, and at the end create new kubernetes client that will use this newly created service account. This kubernetes client should be injected to Operator.

At the moment, `quarkus-operator-sdk` uses default (?) kubernetes client, I wonder if there should be an option to annotate the bean with an annotation, and this particular bean will be picked and used by quarkus.

```kotlin
@Bean
@OperatorKubernetesClient
fun operatorKubernetesClient() = ...
```

When there is no bean with such annotation, then the default one should be used.

What do you think about this? Is there any other option to test such bevahiour?

**Comment by AleksanderBrzozowski** [comment]
@metacosm any thoughts? 🙂 
I could try to make such a change, but I want to know what do you think about it 😉

**Comment by metacosm** [comment]
Actually, looking at it more, what's needed is more documentation I think, not necessarily more code since it's already possible to configure things quite a bit.

**Comment by AleksanderBrzozowski** [comment]
What if I want to have two KubernetesClient beans? 🙂 
One that has admin privileges, and the second one which has only operator privileges?
I think that it is possible to mark one of them as a `Primary`, but I would prefer specific annotation to mark the specific KubernetesClient as the one that should be used in reconciler.

**Comment by metacosm** [comment]
There's nothing that prevents you from creating additional client instances to use in your code. I'm just not sure it makes sense to provide a way for the framework to handle different clients. How would the framework know when to use which client, as this would be application specific? How could this extra support be generic enough and useful outside of your specific application to justify becoming part of the extension / framework?

It might be worthy to think about the testing use case some more but I think that might be better handled at the Quarkus level than here.

**Comment by scrocquesel** [comment]
Quarlus kubernetes client extension do not support named client. Could be a great feature for multi-cluster application.

As for the use case, it seems it is related to how the cluster is set up and should be a concern of the testing framework. Maybe dev services for Kubernetes could be extended to provide k8s resource installation and be able to pass credz of a specific service account.

**Comment by metacosm** [comment]
> Quarlus kubernetes client extension do not support named client. Could be a great feature for multi-cluster application.
> 

That's an interesting idea but I'm not sure this would fit in the extension because this seems to be a rather limited use case which would significantly impact the complexity of the extension, I think.

> 
> 
> As for the use case, it seems it is related to how the cluster is set up and should be a concern of the testing framework. Maybe dev services for Kubernetes could be extended to provide k8s resource installation and be able to pass credz of a specific service account.

That's more along what I was thinking and something I had been planning to tackle in an update to adapt https://github.com/quarkusio/quarkus/issues/25938 to the new dev service paradigm as lots of what is in that PR doesn't really make sense when using the new dev service.

**Comment by AleksanderBrzozowski** [comment]
I was finally able to implement this using config like this:
```kotlin
@Qualifier
@Retention(RUNTIME)
@Target(FUNCTION, VALUE_PARAMETER, FIELD)
annotation class AdminClient

@Singleton
class TestConfig {

    @Produces
    @AdminClient
    @Singleton
    fun adminKubernetesClient(buildConfig: KubernetesClientBuildConfig, tlsConfig: TlsConfig): KubernetesClient =
        KubernetesClientUtils.createClient(buildConfig, tlsConfig)

    @Produces
    @Singleton
    fun operatorKubernetesClient(
        @AdminClient adminClient: KubernetesClient
    ): KubernetesClient {
        val oauthToken = oauthToken() // apply rbac and get the token from secrets
        val adminConfig = adminClient.configuration
        val config = ConfigBuilder(Config.empty())
            .withMasterUrl(adminConfig.masterUrl)
            .withCaCertData(adminConfig.caCertData)
            .withOauthToken(oauthToken)
            .build()
        return KubernetesClientBuilder()
            .withConfig(config)
            .build()
    }
}
```
The operator uses `operatorKubernetesClient` (the default one), and when I want to inject the admin client, I just use the `AdminClient` annotation.

The only thing that bothers me with this solution is the fact that `operatorKubernetesClient` is not explicitly referenced by the Operator 🙂

**Comment by metacosm** [comment]
It shouldn't matter if your producer method is not referenced directly by the operator, the extension is set up so that it provides a default client bean if the application doesn't provide one. Your application now provides a `KubernetesClient` instance so it will use the one that you provide instead of the default one.

**Comment by AleksanderBrzozowski** [comment]
> It shouldn't matter if your producer method is not referenced directly by the operator, the extension is set up so that it provides a default client bean if the application doesn't provide one. Your application now provides a `KubernetesClient` instance so it will use the one that you provide instead of the default one.

Yup, that's true. The framework won't create `KubernetesClient` if it finds that there is existing one already created 🙂 

I will close this issue 🙂 Thanks for help 😉

**Comment by metacosm** [comment]
Thank you, I will make sure to include this topic in the documentation improvements I'm working on. Thank you!
