### ISSUE TITLE
Freshly configured project contains warning - "There are multiple httpclient implementation in the classpath"

### ISSUE THREAD

**Issue by AleksanderBrzozowski** [quarkiverse/quarkus-operator-sdk#595]
I've generated a new project with only quarkus-operator-sdk configured:

```
dependencies {
    implementation(enforcedPlatform("${quarkusPlatformGroupId}:${quarkusPlatformArtifactId}:${quarkusPlatformVersion}"))
    implementation("io.quarkiverse.operatorsdk:quarkus-operator-sdk:6.0.3")
    implementation("io.quarkus:quarkus-arc")
    testImplementation("io.quarkus:quarkus-junit5")
}
``` 

When I run `./gradlew quarkusDev` I got following warning:

```
2023-05-18 13:55:53,684 WARN  [io.fab.kub.cli.uti.HttpClientUtils] (Quarkus Main Thread) There are multiple httpclient implementation in the classpath, choosing the first non-default implementation. You should exclude dependencies that aren't needed or use an explicit association of the HttpClient.Factory.
```

I saw these clients on classpath:

- `kubernetes-httpclient-okhttp-6.5.1.jar`
- `kubernetes-httpclient-vertx-6.5.1.jar`

Can we just keep only one dependency? 🙂

**Comment by metacosm** [comment]
> I've generated a new project with only quarkus-operator-sdk configured:
> 
> ```
> dependencies {
>     implementation(enforcedPlatform("${quarkusPlatformGroupId}:${quarkusPlatformArtifactId}:${quarkusPlatformVersion}"))
>     implementation("io.quarkiverse.operatorsdk:quarkus-operator-sdk:6.0.3")
>     implementation("io.quarkus:quarkus-arc")
>     testImplementation("io.quarkus:quarkus-junit5")
> }
> ```
> 
> When I run `./gradlew quarkusDev` I got following warning:
> 
> ```
> 2023-05-18 13:55:53,684 WARN  [io.fab.kub.cli.uti.HttpClientUtils] (Quarkus Main Thread) There are multiple httpclient implementation in the classpath, choosing the first non-default implementation. You should exclude dependencies that aren't needed or use an explicit association of the HttpClient.Factory.
> ```
> 
> I saw these clients on classpath:
> 
> * `kubernetes-httpclient-okhttp-6.5.1.jar`
> * `kubernetes-httpclient-vertx-6.5.1.jar`
> 
> Can we just keep only one dependency? 🙂

You should indeed only keep one, the vert.x client being the preferred one when using Quarkus. Could you attach a log of your dependencies (in maven, you'd do `mvn dependency:tree, I don't know the Gradle equivalent), please? I'd like to see where the okhttp implementation is coming from, please?

**Comment by metacosm** [comment]
> There is also one more warning:
> 
> ```
> Mismatched JOSDK Fabric8 Kubernetes Client version found: "6.5.1", expected: "6.6.2" by at least a minor version and things might not work as expected.
> ```

Yes, this is currently expected until Quarkus releases a version that uses Fabric8 6.6.2. We've had issues in the past with misaligned versions so we decided to now issue a warning when versions are misaligned by at least a minor version, which is currently the case. While things should be fine, please don't hesitate to file an issue, should you find any.

**Comment by AleksanderBrzozowski** [comment]
> You should indeed only keep one, the vert.x client being the preferred one when using Quarkus. Could you attach a log of your dependencies (in maven, you'd do `mvn dependency:tree, I don't know the Gradle equivalent), please? I'd like to see where the okhttp implementation is coming from, please?

```
+--- io.quarkiverse.operatorsdk:quarkus-operator-sdk:6.0.3
|    +--- io.javaoperatorsdk:operator-framework-core:4.3.3
|    |    +--- io.fabric8:kubernetes-client:6.6.2 -> 6.5.1
|    |    |    +--- io.fabric8:kubernetes-httpclient-okhttp:6.5.1
|    +--- io.quarkus:quarkus-openshift-client:3.0.3.Final
|    |    +--- io.quarkus:quarkus-kubernetes-client:3.0.3.Final
|    |    |    +--- io.fabric8:kubernetes-httpclient-vertx:6.5.1
```

The whole dependency tree is quite big, this should be enough though.

**Comment by AleksanderBrzozowski** [comment]
> Yes, this is currently expected until Quarkus releases a version that uses Fabric8 6.6.2. We've had issues in the past with misaligned versions so we decided to now issue a warning when versions are misaligned by at least a minor version, which is currently the case. While things should be fine, please don't hesitate to file an issue, should you find any.

Understood. Shouldn't we then keep a matrix of which `quarkus` version should be used with `quarkus-operator-sdk` to avoid this conflict?

I guess that k8s client version should match between `quarkus` and `java-operator-sdk`?

**Comment by metacosm** [comment]
> > You should indeed only keep one, the vert.x client being the preferred one when using Quarkus. Could you attach a log of your dependencies (in maven, you'd do `mvn dependency:tree, I don't know the Gradle equivalent), please? I'd like to see where the okhttp implementation is coming from, please?
> 
> ```
> +--- io.quarkiverse.operatorsdk:quarkus-operator-sdk:6.0.3
> |    +--- io.javaoperatorsdk:operator-framework-core:4.3.3
> |    |    +--- io.fabric8:kubernetes-client:6.6.2 -> 6.5.1
> |    |    |    +--- io.fabric8:kubernetes-httpclient-okhttp:6.5.1
> |    +--- io.quarkus:quarkus-openshift-client:3.0.3.Final
> |    |    +--- io.quarkus:quarkus-kubernetes-client:3.0.3.Final
> |    |    |    +--- io.fabric8:kubernetes-httpclient-vertx:6.5.1
> ```
> 
> The whole dependency tree is quite big, this should be enough though.

That's weird because I don't get the okhttp dependency on my side.

**Comment by AleksanderBrzozowski** [comment]
which quarkus version do you use?
I have:
```
#Gradle properties
quarkusPluginId=io.quarkus
quarkusPluginVersion=3.0.3.Final
quarkusPlatformGroupId=io.quarkus.platform
quarkusPlatformArtifactId=quarkus-bom
quarkusPlatformVersion=3.0.3.Final
```
Do you have the same dependency versions as I have? 🙂

**Comment by metacosm** [comment]
Well, your tree is showing that the okhttp HTTP client implementation for fabric8 is coming from QOSDK, which I don't see here, i.e. it doesn't show up at all in the dependency tree for the extension. The only mention of okhttp at all is coming from the Fabric8 mock server and that's scoped with a test scope (and that's okhttp itself, not the fabric8 http client implementation), so I'm quite surprised about it showing up there.

**Comment by AleksanderBrzozowski** [comment]
The tree was generated using following command:
```
./gradlew -q dependencies --configuration runtimeClasspath
```

It doesn't contain test dependencies.

Can you share the command that you use to list extension dependencies?

**Comment by metacosm** [comment]
At the root of the extension project, I just run `mvn dependency:tree`.

**Comment by AleksanderBrzozowski** [comment]
> At the root of the extension project, I just run `mvn dependency:tree`.

Heh, you are right, it doesn't contain okhttp dependency, it is weird. I will investigate it then 🤔

**Comment by metacosm** [comment]
The platform BOM is only needed if you intend to use multiple supported Quarkus extensions at once, this will enforce that all the dependencies are aligned. If you don't need any other extension than the JOSDK one, then using the non-platform BOM is enough (this only brings the Quarkus dependencies, not all the other dependencies needed for other supported projects).
That said, typical user applications should use the platform BOM, indeed. In this case, though, I'm curious to see if using the non-platform BOM would make a difference, and if it does, we probably need to figure out where this is coming from at the Quarkus level and address the issue because if the okhttp client dependency is indeed brought by the platform, it should be fixed.

**Comment by metacosm** [comment]
Yes, there's probably something maven-related since the dependency is marked as optional in maven. I'm not sure how the same can be accomplished with Gradle as I don't know enough about Gradle.

**Comment by AleksanderBrzozowski** [comment]
I am closing the issue, the warning has gone with the newest version 👍

**Comment by metacosm** [comment]
Weird but glad the issue is fixed. Would have liked to understand why this was happening before and why it's now gone but 🤷🏼
