### ISSUE TITLE
Bundle generator splits output files when a different name is specified

### ISSUE THREAD

**Issue by ASzc** [quarkiverse/quarkus-operator-sdk#608]
When a different bundle name to the default is specified on the reconciler class, using the `@CSVMetadata` annotation's `name` field, there's a weird behavior where the output files are split between the a directory with the default name, and a directory with the specified `name` value:

```
aszczucz@tyrfing ~/s/k/k/operator (issue_10911)> tree target/bundle/keycloak-operator*
target/bundle/keycloak-operator
├── bundle.Dockerfile
├── manifests
│   ├── keycloak-operator.clusterserviceversion.yaml
│   └── keycloakrealmimports.k8s.keycloak.org-v1.crd.yml
└── metadata
    └── annotations.yaml
target/bundle/keycloak-operator.KCOP_NEXT
├── bundle.Dockerfile
├── manifests
│   ├── keycloak-operator.KCOP_NEXT.clusterserviceversion.yaml
│   └── keycloaks.k8s.keycloak.org-v1.crd.yml
└── metadata
    └── annotations.yaml
```

The CSV in the default directory is incomplete, and doesn't contain the information specified with `@CSVMetadata`. However, in my case I am also seeing that the CRDs are split between the two directories. `keycloaks.k8s` is only in the new directory, and `keycloakrealmimports.k8s` is only in the default directory.

The expected behaviour here is that there should be only one bundle output directory, and that should contain all appropriate CRDs and a CSV with all the annotated information from the source code.

If I had to guess, this bug may be due to some processing happening before the default name value is overwritten, and then some more processing happening afterwards?

Please see [this commit](https://github.com/keycloak/keycloak/blob/e81671482eede336d27f026c26b4a8f9e95e9041/operator/src/main/java/org/keycloak/operator/controllers/KeycloakController.java) for the annotated reconciler source I am using. The operator SDK version is 6.1.0, the latest.

**Comment by metacosm** [comment]
This is actually expected as you have 2 reconcilers in your operator and we currently generate one bundle per reconciler by default, so you get two bundles, as expected. If you want to generate only one bundle for all your reconcilers, please put your metadata on a class that implements the `SharedCSVMetadata` interface as can be seen [here](https://github.com/quarkiverse/quarkus-operator-sdk/blob/04ae400456d026897b4ba0aea9458fe38196a1bd/samples/pingpong/src/main/java/io/quarkiverse/operatorsdk/samples/pingpong/PingPongOperatorCSVMetadata.java#L8).

**Comment by ASzc** [comment]
I will have to ask why there are two, I don't really know anything about this codebase. Thanks for clarifying that this isn't a bug, closing.

**Comment by metacosm** [comment]
You have 2 reconcilers because there's one per primary resource (CRD) that you're reconciling on.
