### ISSUE TITLE
Slow cleanup when stopping the Quarkus application - Log message needed?

### ISSUE THREAD

**Issue by gsmet** [quarkiverse/quarkus-operator-sdk#652]
Note: this is just a developer experience issue.

I have seen a demo of a Quarkus Operator at Riviera DEV and when stopping the application, we have the message saying that the Quarkus application is stopped... and then you have to wait ~10 seconds before the application actually stops.

I suppose either this extension or the Kubernetes Client is doing some cleanup tasks at the end but it's a bit confusing as I didn't see anything in the log telling me that something was in progress.

Ideally, it would be nice if the cleanup task could be executed before the Quarkus stopped message is actually displayed.

**Comment by gsmet** [comment]
Also it might have been the shutdown of the Kubernetes dev services so maybe it's there that we need to add a message.

It would be nice if you could have a look what's going on.

**Comment by metacosm** [comment]
I am not sure what was going on but I haven't noticed any particular delay when shutting down applications. Will close this issue, please re-open with more details if you think this is necessary.
