### ISSUE TITLE
quarkus-operator-sdk-bundle-generator generated bundle missing ServiceAccounts

### ISSUE THREAD

**Issue by Jeansen** [quarkiverse/quarkus-operator-sdk#681]
When I build my test operator (wit gradle), I have a folder build/kubernetes containing a yaml and json file with ServiceAccounts, Deployment and a Service. The file created in build/bundle with the ClusterServiceVersion, only contains a Deployment.

Is this by design, or shouldn't be everything from the kubernetes folder added to the bundle, too?

**Comment by metacosm** [comment]
Are you talking about a `kubernetes.json|yaml` file in the `bundle` directory? If yes, there shouldn't be one. Is your code available for us to check what's going on?

**Comment by Jeansen** [comment]
@metacosm Yes, I am talking about the file `bundle/kuberntes/kubernetes.json|yaml`. Here is my little playground: https://github.com/Jeansen/cert-operator

**Comment by metacosm** [comment]
> @metacosm Yes, I am talking about the file `bundle/kuberntes/kubernetes.json|yaml`. Here is my little playground: https://github.com/Jeansen/cert-operator

So I checked your project and, as expected, there is no `bundle/kubernetes/kubernetes.json|yml` file, nor should there be one. Maybe I'm missing something to replicate what you're seeing? Note that I'm not super familiar with gradle so maybe I did something wrong? 

If I didn't do anything wrong, if you're talking about the `kubernetes/kubernetes.yml` file instead then this file is not generated by this extension or the bundle generator, but rather by the Quarkus kubernetes extension and appears to properly contain a generated ServiceAccount. 

If you're talking about the `build/bundle/cert-operator/manifests/cert-operator.clusterserviceversion.yaml` file, then it is expected that this file doesn't contain a service account. This is information used by OLM to deploy your operator and it proceeds in a different way than what you'd expect from a `kubectl apply` (for which you'd use the `build/kubernetes/kubernetes.yml` file instead). Note also that starting from 6.3.0, the extension also offers Helm chart generation, which is yet another option to deploy your operator. 

Hope this helps. If not, let me know.

**Comment by Jeansen** [comment]
Hi @metacosm.
Uhm...my bad. You are right, there is no `bundle/kubernetes/kubernetes.json|yaml` file. It is `kubernetes/kubernetes/` where these two files exist. I am sorry for the unnecessary confusion. Regarding the `build/bundle/cert-operator/manifests/cert-operator.clusterserviceversion.yaml` file: In the last days I read a bit more and retried my depolyment. I think I had some sort of a broken state because now, it works fine. I created a catalog, added the operator to it, created a group and subscription and the operator got deployed without errors. In addition, your recent code addition made ich much easier, without any intervention. I could directly pick up the bundle and continue from there on.

Thank you for your quick reaction and again, I am sorry for the confusion.

**Comment by Jeansen** [comment]
> kubernetes.io Java

I don't need it. That's from an early stage when I started of. I thought about not using the fabric8 part, but quickly put that thought aside ;-)
