### ISSUE TITLE
Make it possible to mark primary CR as unowned

### ISSUE THREAD

**Issue by metacosm** [quarkiverse/quarkus-operator-sdk#704]
Some reconcilers are acting as additional reconcilers for resources that are primarily handled by another reconciler (e.g. a `Deployment` custom reconciler might add annotations or watch deployments to perform additional behavior but the primary `Deployment` reconciler is part of the Kubernetes platform). 
In this situation, it should be possible to mark the primary resource associated with that reconciler as unowned so that it isn't considered for CRD generation and is marked accordingly as required or native API (if it's a native Kubernetes resource) in the generated bundle.         

_See https://github.com/quarkiverse/quarkus-operator-sdk/issues/674#issuecomment-1706037327_

/cc @Obirah

**Comment by Obirah** [comment]
> @Obirah could you give #703 a try, please, and let me know if that addresses your use case?

Of course, I'm happy to help - the approach already looks good! Does your branch automatically create a pre-release of the operator-sdk that I can include in my Gradle project or is there another simple way to test it under "real conditions"?

**Comment by metacosm** [comment]
> > @Obirah could you give #703 a try, please, and let me know if that addresses your use case?
> 
> Of course, I'm happy to help - the approach already looks good! Does your branch automatically create a pre-release of the operator-sdk that I can include in my Gradle project or is there another simple way to test it under "real conditions"?

No, you'd have to check out the branch and build it locally, unfortunately.
