### ISSUE TITLE
Generated OLM Bundle is not usable out of the box 

### ISSUE THREAD

**Issue by jcechace** [quarkiverse/quarkus-operator-sdk#711]
There are two primary issues with the generated OLM Bundle 

### OLM standard for configuraing watched namespaces is via `olm.targetNamespaces` annotation  whereas QOSKD uses `QUARKUS_OPERATOR_SDK_NAMESPACES` for the exact same purpose (in boh cases empty value means "watch all")

This can be easily remedied by generating the equivalend of the follwing `yq` command

```bash
yq ea -i '.spec.install.spec.deployments[0].spec.template.spec.containers[0].env += [{"name": "QUARKUS_OPERATOR_SDK_NAMESPACES", "valueFrom": {"fieldRef": {"fieldPath": "metadata.annotations['"'"'olm.targetNamespaces'"'"']"}}}]' "$CSV_PATH"
```

### The `@CSVMetadata` annotation is too static -- in a sense that it doesn't allow setting values from properties. Modifying the sourcecs to change e.g. `spec.replaces` of the generated CSV is not really practical.

This could be improved (for example) by one of the following 

1) Introduce new @CsvMetadata.ConfigValue("prop.name") annotation which could be used as the following

```java
@CSVMetadata(replaces = @CsvMetadata.ConfigValue("dbz.version.prev"))
DebeziumCsvMetadata
```

This has of course the downside of `replaces` no longer being a plain string. So we would have to figure out a more polished approach

2) Simply make all CSV metadata defaults configurable via properties. So one would siply set a property during buld  (or in application.properties) e.g. `quarkus.operator-sdk.bundle.metadata.replaces=X.Y.Z`

This might be of course a bit more complex for metadata which are not a simple type (e.g. installModes)

**Comment by jcechace** [comment]
Both us ([debezium](https://github.com/jcechace/debezium-operator/blob/DBZ-6738/scripts/create-olm-bundle.sh)) and [KeyCloak](https://github.com/keycloak/keycloak/blob/main/operator/scripts/create-olm-bundle.sh) are currently running a postporcessing script in bash in order to fix this.

**Comment by metacosm** [comment]
Which version of QOSDK are you using?

**Comment by jcechace** [comment]
I managed to make this work with just maven, however it requires some serious maven gymnastics 

https://github.com/debezium/debezium-operator/pull/9/files#diff-9c5fb3d1b7e3b0f54bc5c4182965c4fe1f9023d449017cece3005d3f90e8e4d8R239

**Comment by jcechace** [comment]
> Which version of QOSDK are you using?

6.3.0

**Comment by metacosm** [comment]
> > Which version of QOSDK are you using?
> 
> 6.3.0

Doesn't appear to be the case: https://github.com/debezium/debezium-operator/blob/main/pom.xml#L34

**Comment by jcechace** [comment]
> > > Which version of QOSDK are you using?
> > 
> > 
> > 6.3.0
> 
> Doesn't appear to be the case: https://github.com/debezium/debezium-operator/blob/main/pom.xml#L34

It does appear to be the case https://github.com/debezium/debezium-operator/pull/9/files#diff-9c5fb3d1b7e3b0f54bc5c4182965c4fe1f9023d449017cece3005d3f90e8e4d8R47

OLM integration is just not merged yet (this PR was linked here multiple times ;))

**Comment by metacosm** [comment]
> There are two primary issues with the generated OLM Bundle
> ### OLM standard for configuraing watched namespaces is via `olm.targetNamespaces` annotation whereas QOSKD uses `QUARKUS_OPERATOR_SDK_NAMESPACES` for the exact same purpose (in boh cases empty value means "watch all")

That is not really true. First, `QUARKUS_OPERATOR_SDK_NAMESPACES` is meant to provide a default value for all controllers if **none** is set at the controller level. While it can be used to control the namespaces watched by a given controller, it's better to set it explicitly for each controller. 

That said, this value is a runtime property, i.e. it is not used at build time when descriptors are generated. See https://github.com/quarkiverse/quarkus-operator-sdk/releases/tag/6.2.1 for details on why the change was made and https://docs.quarkiverse.io/quarkus-operator-sdk/dev/index.html#quarkus-operator-sdk_quarkus.operator-sdk.namespaces and more specifically https://docs.quarkiverse.io/quarkus-operator-sdk/dev/index.html#quarkus-operator-sdk_quarkus.operator-sdk.controllers.-controllers-.generate-with-watched-namespaces for more details about each property.

That said, they still might be issues that need to be addressed, especially considering that we're not OLM experts by any means.

**Comment by metacosm** [comment]
> > > > Which version of QOSDK are you using?
> > > 
> > > 
> > > 6.3.0
> > 
> > 
> > Doesn't appear to be the case: https://github.com/debezium/debezium-operator/blob/main/pom.xml#L34
> 
> It does appear to be the case https://github.com/debezium/debezium-operator/pull/9/files#diff-9c5fb3d1b7e3b0f54bc5c4182965c4fe1f9023d449017cece3005d3f90e8e4d8R47
> 
> OLM integration is just not merged yet (this PR was linked here multiple times ;))

Indeed, missed that. My bad! 😅

**Comment by shawkins** [comment]
> how do you configure the watch namespaces (scope of the operator) then? Like the generated CSV doesn't add the QUARKUS_OPERATOR_SDK_NAMESPACES and JOSDK doesn't support the configuration of watched namespaces via the OLM annotation

You'd current have to do something like:

quarkus.kubernetes.env.fields."quarkus.operator-sdk.namespaces"=metadata.annotations['olm.targetNamespaces']

Or if you have a deployment fragment, add in something similar.

However that does seem cumbersome - this is something that the sdk could take care of.

**Comment by jcechace** [comment]
> > how do you configure the watch namespaces (scope of the operator) then? Like the generated CSV doesn't add the QUARKUS_OPERATOR_SDK_NAMESPACES and JOSDK doesn't support the configuration of watched namespaces via the OLM annotation
> 
> You'd current have to do something like:
> 
> quarkus.kubernetes.env.fields."quarkus.operator-sdk.namespaces"=metadata.annotations['olm.targetNamespaces']
> 
> Or if you have a deployment fragment, add in something similar.
> 
> However that does seem cumbersome - this is something that the sdk could take care of.

Except this will influence the genreated kubernetes.yaml as well and it might be problematic if you want to deploye without OLM support... Having the variable generated in kubernetes.yaml is a good idea, however one ought ot be able to override the value for OLM bundle specifically 


So I would suggest adding the QUARKUS_OPERATOR_SDK_NAMESPACES variable to operator deployments by default (with the value based on `ControllerConfiguration.namespaces` and defaulting to empty value -- which on runtime equals to "JOSDK_ALL_NAMESPACES"). Then during OLM bundle processing the value would exchanged for the OLM annotation reference.

**Comment by shawkins** [comment]
> Except this will influence the genreated kubernetes.yaml as well and it might be problematic if you want to deploye without OLM support... Having the variable generated in kubernetes.yaml is a good idea, however one ought ot be able to override the value for OLM bundle specifically

The issue with non-olm installations will be if you want a default that is something other than watch all.  I had addressed this in an earlier pr we didn't end up persuing by differentiating between an empty string and a missing value https://github.com/keycloak/keycloak/pull/21231/files#diff-9b07f581e866b9bfaad90cb404bb0f56f5b7c05226d10e40485a8b16f1694048R39 to instead use the default.  With all of the subsequent changes around this in the JOSDK, I'm not sure if that is even necessary.

However I can understand the qualm of not wanting to use the olm annotation even for non-olm deployments.

**Comment by jcechace** [comment]
> > Except this will influence the genreated kubernetes.yaml as well and it might be problematic if you want to deploye without OLM support... Having the variable generated in kubernetes.yaml is a good idea, however one ought ot be able to override the value for OLM bundle specifically
> 
> The issue with non-olm installations will be if you want a default that is something other than watch all. I had addressed this in an earlier pr we didn't end up persuing by differentiating between an empty string and a missing value https://github.com/keycloak/keycloak/pull/21231/files#diff-9b07f581e866b9bfaad90cb404bb0f56f5b7c05226d10e40485a8b16f1694048R39 to instead use the default. With all of the subsequent changes around this in the JOSDK, I'm not sure if that is even necessary.
> 
> However I can understand the qualm of not wanting to use the olm annotation even for non-olm deployments.

This was fixed in one of the latest releases. Prior the QUARKUS_OPERATOR_SDK_NAMESPACES was ovreloaded and had slightly different meaning on runtime and build time. QUARKUS_OPERATOR_SDK_GENERATE_WITH_WATCHED_NAMESPACES fixed that IIRC
