### ISSUE TITLE
Exhausted retries and  UpdateControl Not working properly 

### ISSUE THREAD

**Issue by chethankumar4046** [quarkiverse/quarkus-operator-sdk#718]
How to configure Exhausted retries.
operator-sdk.version 4.0.3

Reconciler trying execute multiple times when there is a  error in Reconciler, 
But i want to configure such a way that No need Reconciler multiple time. How to do

 error 
 2023-09-21 06:57:23,105 ERROR [io.jav.ope.pro.eve.EventProcessor] (ReconcilerExecutor--65) Exhausted retries for ExecutionScope{ resource id: ResourceID{name='test', namespace='default'}, version: 416164383},
 
 
And 

I am updating UpdateControl below way but it is not working 

return UpdateControl.updateStatus(test);

When custom operator restart it trying  to Reconciler again

**Comment by csviri** [comment]
> When custom operator restart it trying to Reconciler again

It's a basic principle that when operators restart it reconciles all the resources. There is no way around this, other that maybe putting some state that this should not be fully reconciled again and explicitly handling that on the reconcile start.

**Comment by csviri** [comment]
This issue belongs more to core JOSDK, we should move it there probably.

**Comment by csviri** [comment]
> I am updating UpdateControl below way but it is not working

what do you mean by this?

**Comment by chethankumar4046** [comment]
> > When custom operator restart it trying to Reconciler again
> 
> It's a basic principle that when operators restart it reconciles all the resources. There is no way around this, other that maybe putting some state that this should not be fully reconciled again and explicitly handling that on the reconcile start.
@csviri Thanks for your replay,

**Comment by chethankumar4046** [comment]
@csviri Can you comment on Exhausted retries.

**Comment by chethankumar4046** [comment]
Okay. How to configure Reconciler to retry if there is a error in or  Reconciler like deployment, Job etc...

https://quarkus.io/guides/smallrye-fault-tolerance

**Comment by csviri** [comment]
Ahh, ok, so:

> https://quarkus.io/guides/smallrye-fault-tolerance

this is not used in JOSDK/QOSDK.
See docs for built in retry: https://javaoperatorsdk.io/docs/features#automatic-retries-on-error

Retry handles only java exception, so if you want to retry because there is some error in the deployment (status field), you have to manage it yourself. If this is what you mean. (see `UpdateControl.reSchedule`)

**Comment by chethankumar4046** [comment]
> Ahh, ok, so:
> 
> > https://quarkus.io/guides/smallrye-fault-tolerance
> 
> this is not used in JOSDK/QOSDK. See docs for built in retry: https://javaoperatorsdk.io/docs/features#automatic-retries-on-error
> 
> Retry handles only java exception, so if you want to retry because there is some error in the deployment (status field), you have to manage it yourself. If this is what you mean. (see `UpdateControl.reSchedule`)

Thanks a lot.

**Comment by metacosm** [comment]
Closing this issue as it's not relevant to this project and it's being addressed in JOSDK.
