### ISSUE TITLE
CSVMetadata.name is confusing in some cases (e.g. when providing meta information for CRDs

### ISSUE THREAD

**Issue by jcechace** [quarkiverse/quarkus-operator-sdk#738]
`CSVMetadata.name` is used for several things currently

1. To set the bundle name
2. To group together various objects related to the same bundle

These points are in some way problematic

- A bundle name usually contains a version which changes over time, however the "grouping" identifier would ideally be static 
- In some cases the `CSVMetadata` annotation as a whole is used to provide metadata for just a part of the resulting `CSV`. Such is the case for `.spec.customresourcedefinitions.owned[]` property. However the CRD definitions in this case also contain a `name` attribute. While it doesn't make sense to change the value of this attribute, it is confusing when one uses the `CSVMetadata.name` over the CR Java class in order to group the metadata into the correct bundle. 

Related [discussion on Discord](https://discord.com/channels/723455000604573736/786172306804047932/1159503558836748328)

**Proposal:**

Introduce `CSVMetadata.bundle` which would act as the "grouping" identifier and have ``CSVMetadata.name` default to `CSVMetadata.bundle` when processing the top level `CSVMetadata` annotation (that is the instance placed over either the controller class or class implementing `SharedCSVMetadata`).

It might also be worth considering whether metadata for specific parts of `CSV` (e.g. the `customresourcedefinitions` should be set using the generic `CSVMetadata` annotation as in this case the majority of its attributes does not apply -- however I don't consider this to be a major issue if the above confusion is removed.

**Comment by metacosm** [comment]
Let me know what you think about the PR, see if this improves things.
