### ISSUE TITLE
enhancement: global controllers configuration

### ISSUE THREAD

**Issue by lburgazzoli** [quarkiverse/quarkus-operator-sdk#74]
I have 3 controllers in my operator and with the current configuration set-up I have to individually configure them, like:

```
quarkus.operator-sdk.controllers."A".generation-aware = false
quarkus.operator-sdk.controllers."A".namespaces = ${my.namespace}
quarkus.operator-sdk.controllers."B".generation-aware = false
quarkus.operator-sdk.controllers."B".namespaces = ${my.namespace}
quarkus.operator-sdk.controllers."C".generation-aware = false
quarkus.operator-sdk.controllers."C".namespaces = ${my.namespace}
```

I think it would be nice to have also a top leve netry that can be used to configure common behaviors, like:

```
quarkus.operator-sdk.controllers.namespaces = ${cos.namespace}
quarkus.operator-sdk.controllers.generation-aware = false
```

and then, individual controllers can override the default value if needed

**Comment by metacosm** [comment]
Note that it's not possible to set properties such as `quarkus.operator-sdk.controllers.namespaces=foo`, the operator-level properties are defined under the `quarkus.operator-sdk` path directly, e.g. `quarkus.operator-sdk.namespaces=foo` in #78.
