### ISSUE TITLE
Support for requeue in UpdateControl

### ISSUE THREAD

**Issue by Obirah** [quarkiverse/quarkus-operator-sdk#744]
The go operator-sdk allows to requeue reconciliations, see [docs](https://sdk.operatorframework.io/docs/building-operators/golang/tutorial/#reconcile-loop). As far as I can see, there is no corresponding functionality in the Quarkus operator-sdk, yet. If I'm overlooking it, please correct me and close this issue.

It would be cool to be able to optionally pass the requeue properties in `UpdateControl` so that the reconciliation is retried in x minutes.

In order to give you more context here's my use-case: one condition of my reconciliation relies on an external change whose status I can only poll - namely an AWS support case being resolved. Hence, during the first reconciliation I'm fulfilling all conditions that I can fulfill immediately and then I need to requeue until the support case condition has a resolved or a failed status.

**Comment by metacosm** [comment]
You can reschedule after a given amount of time using `UpdateControl.rescheduleAfter`. However, your use case is probably best modeled using a `DependentResource` tracking the external state as described in https://javaoperatorsdk.io/docs/dependent-resources#external-state-tracking-dependent-resources. A `PollingDependentResource` would probably work and would avoid triggering your reconciler if not needed, which would be the case if you reschedule a reconciliation after a delay and no changes occurred in the external state. This would also better encapsulate the external state management.
