### ISSUE TITLE
Rate limiting does not work as expected in Quarkus

### ISSUE THREAD

**Issue by gavin15** [quarkiverse/quarkus-operator-sdk#756]
On the reconciler class i'm using `RateLimited` annotation but it never seems to get processed by Quarkus. 

e.g.

```
@ControllerConfiguration(
        name = "test-reconciler",
        rateLimiter = QuarkusControllerConfiguration.DefaultRateLimiter.class
)
@RateLimited(maxReconciliations = 1, within = 1, unit = TimeUnit.MINUTES)
public class MyReconciler implements Reconciler<MyCR>, EventSourceInitializer<MyCR>, ErrorStatusHandler<MyCR>, Cleaner<MyCR> {
.
.
.
}
```

I can see this working outside of Quarkus (i.e. new Operator().register(reconciler)) and this works as expected.

i've had a quick look at the code [here](https://github.com/quarkiverse/quarkus-operator-sdk/blob/11ba19f35c1485fdf45482b3e42922be579e468a/core/runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/QuarkusControllerConfiguration.java#L138-L140) where `rateLimiterClass` and `rateLimiter` are set but i'm not sure what `rateLimiterConfigurationClass` is supposed to be or how we set it. 

If i understand correctly it looks like the annotations get processed if there's a configuration class in https://github.com/quarkiverse/quarkus-operator-sdk/blob/11ba19f35c1485fdf45482b3e42922be579e468a/core/runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/QuarkusControllerConfiguration.java#L399-L407, given it's null i presume this is why it's not working. 

Can someone explain if there's an issue here or how I get my rate limiter configuration working, please.

Version: quarkus-operator-sdk 6.3.3

**Comment by metacosm** [comment]
Confirmed that there is an issue. Working on it.

**Comment by gavin15** [comment]
Thanks a lot for fixing this @metacosm! Presumably this will be picked up in 6.4.1?

**Comment by metacosm** [comment]
I was thinking about going straight to 6.5.0 with Quarkus 3.6.0 support (which should be released tomorrow). Would that work for you?

**Comment by gavin15** [comment]
yes that would work, thanks!

**Comment by metacosm** [comment]
I've released 6.5.0.Beta2 if you want to give it a try (we do not talk about 6.5.0.Beta1! 😅 )

**Comment by gavin15** [comment]
@metacosm thanks for that! We're in the process of moving up from 6.3.3, I will get back to you with the results once we're there.
Having said that, I tried patching 6.3.3 with your fix locally and could see this working as expected.

**Comment by metacosm** [comment]
Thank you for the update.
