### ISSUE TITLE
Deprecated CSV-related annotations are ignored in the generated bundle

### ISSUE THREAD

**Issue by vmuzikar** [quarkiverse/quarkus-operator-sdk#770]
The annotations that were deprecated in https://github.com/quarkiverse/quarkus-operator-sdk/commit/e646ede9b4fca166c262a4afd66eb3003f3137fb are not reflected in the generated CSV. Deprecated features should work until removed.

Related issue: https://github.com/keycloak/keycloak/issues/24984

**Comment by metacosm** [comment]
This actually isn't trivial to support both versions at the same time so this might not get fixed. Will see depending on need.

**Comment by metacosm** [comment]
Yeah, that's what I'm considering for the next release.

**Comment by metacosm** [comment]
I've created a PR to address this: instead of just removing the deprecated versions, which would lead to compilation errors without explanations, the extension now detects all uses of them and fails the build with a complete report of what needs to be updated.
