### ISSUE TITLE
UnrecognizedPropertyException for field observedGeneration in native mode

### ISSUE THREAD

**Issue by Javatar81** [quarkiverse/quarkus-operator-sdk#824]
I have a class that extends `ObservedGenerationAwareStatus` and thus inherits the field `observedGeneration`. I also registered it for reflection because the CustomResources are in a project pulled into the main project via maven dependency. 

```
@RegisterForReflection
public class GiteaRepositoryStatus extends ObservedGenerationAwareStatus {

...

}
```

When I run my operator as native executable, I get the following error:

```
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "observedGeneration" (class io.devjoy.gitea.k8s.model.GiteaStatus), not marked as ignorable (one known property: "conditions"])
61
at [Source: (BufferedInputStream); line: 1, column: 4515] (through reference chain: io.fabric8.kubernetes.api.model.DefaultKubernetesResourceList["items"]->java.util.ArrayList[0]->io.devjoy.gitea.k8s.model.Gitea["status"]->io.devjoy.gitea.k8s.model.GiteaStatus["observedGeneration"])
```

The CRD resource manifest is generated correctly and contains the observedGeneration field.

**Comment by metacosm** [comment]
I've opened a #826 that should address both your native issues. Let me know how it goes!
