### ISSUE TITLE
Allow to use placeholder in Controller annotation

### ISSUE THREAD

**Issue by lburgazzoli** [quarkiverse/quarkus-operator-sdk#84]
The `Controller` annotation, has an option to set the namespaces a controller should monitor:

```java
public @interface Controller {
  /**
   * Specified which namespaces this Controller monitors for custom resources events. If no
   * namespace is specified then the controller will monitor all namespaces by default.
   *
   * @return the list of namespaces this controller monitors
   */
  String[] namespaces() default {};
}
```

But those option will be then fixed at build time.
To be bale to select what namespace a controller should monitor at runtime, a quarkus option can be set, like::

```
quarkus.operator-sdk.controllers."my-controller".namespaces = "my-namespace"
```

This is fine but the option is not very env var friendly so I wonder if it could make sense to let the `Controller` annotation to accept namespaces defined as placeholder, like:

 ```java
@Controller(namespaces = "{my.namespace}")
```

This would allow to configure the namespace by setting i.e. and var var like

```
MY_NAMESPACE=foo
```

**Comment by lburgazzoli** [comment]
Same thing would apply to configure label selector, like

```
@Controller(
    lableSelector = "app=${foo},type=${bar}"
)
```

**Comment by metacosm** [comment]
The problem with this is that this would require runtime processing of the annotation which would be contrary to the Quarkus philosophy to do as much at build time as possible.

**Comment by lburgazzoli** [comment]
agree, but those are not properties that can be fixed at build time
as far as I know even today, you can override some annotation values using properties (i.e. the namesapces) so it is effectively the same as doing runtime processing ? 

I guess at build time, we can set the configuration and then at runtime, the placeholders are resolved, would that work ?

**Comment by metacosm** [comment]
Note that you should be able to do: `quarkus.operator-sdk.controllers."my-controller".namespaces = ${MY_NAMESPACE}` right now already.

**Comment by lburgazzoli** [comment]
> Note that you should be able to do: `quarkus.operator-sdk.controllers."my-controller".namespaces = ${MY_NAMESPACE}` right now already.

yes I know, but since the same options are configurable also at the annotation level, I think, the behavior should be the same. 
Using properties placeholder in annotations is something that already exists for the scheduler (https://quarkus.io/guides/scheduler-reference) 

btw, I don't have any strong business need for this feature so if it is something we do not want to include in the extension, I'm perfectly fine to close this issue.

**Comment by metacosm** [comment]
I'd rather leave it configurable as is for now, unless there's a strong need for it. Closing for now.
