### ISSUE TITLE
Closing websocket io.fabric8.kubernetes.client.vertx.VertxWebSocket

### ISSUE THREAD

**Issue by GopiChandra25** [quarkiverse/quarkus-operator-sdk#847]
Hi Team,
Currently am working on creating Operator using Quarkus SDK framework.
quarkus-sdk.version : 6.1.1

Operator has reconciliation loop run every 500 seconds and also we wrote logic to override based on user requirement using CR object configuration and also it has one cronjob as dependent resource.

Operator is working fine util it getting connection issue with Kubernetes API server for some time.
During Connection issue between Operator to K8s api server getting below Connection reset error.
**ERROR [io.ver.cor.net.imp.ConnectionBase] (vert.x-eventloop-thread-7) Connection reset: java.net.SocketException: Connection reset
at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:394)
at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:426)**

and we found
**[io.fab.kub.cli.dsl.int.AbstractWatchManager] (vert.x-eventloop-thread-7) Force closing the watch io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager@c00f5e3
DEBUG [io.fab.kub.cli.dsl.int.WatcherWebSocketListener] (vert.x-eventloop-thread-7) WebSocket error received: io.vertx.core.http.HttpClosedException: Connection was closed**

Later this if connection is restored and operator reconciliation loop successfully executing with older version of the CR object, it not identifying and reacting any changes on CR object as well dependent resource object

Can you please help us how to reload or restart websocket connection 

Note: kubeclient is functional after restore k8s api server. We are using OCP4 env to run this Operator.

**Comment by metacosm** [comment]
My first question is why do you run a loop? The operator should be notified if any of the watched resources change and therefore polling shouldn't be necessary. 
Is there a particular reason you're not using the latest version?

**Comment by csviri** [comment]
There were improvements regarding to this in fabric8 client (although not sure if since that version), simply updating to most recent version might fix it.

**Comment by GopiChandra25** [comment]
@csviri thank you updated my quarkus-sdk.version version from 6.1.1 to 6.4.0, issue is fixed

**Comment by metacosm** [comment]
> @csviri thank you updated my quarkus-sdk.version version from 6.1.1 to 6.4.0, issue is fixed

Why didn't you update to the latest one, which 6.6.4?

**Comment by GopiChandra25** [comment]
@metacosm Not sure. I thought 6.4.0 was the latest release; I will update to 6.6.4 and tested it now. Working as expected.
Thank you so much for you Info.
