### ISSUE TITLE
With `quarkus:dev` mode it should be possible to select which CRD to apply

### ISSUE THREAD

**Issue by andreaTP** [quarkiverse/quarkus-operator-sdk#867]
From: https://github.com/fabric8io/kubernetes-client/issues/5867#issuecomment-2058442434

It should be possible to select which CRD to be applied to cover the case when the `java-generator` is used instead of the `crd-generator`.

**Comment by metacosm** [comment]
@matteriben is this still something you are interested in?

**Comment by matteriben** [comment]
@metacosm thank you!
