### ISSUE TITLE
Configuring `maxReconciliationInterval` at runtime

### ISSUE THREAD

**Issue by MikeEdgar** [quarkiverse/quarkus-operator-sdk#893]
I couldn't find a way to set/override `maxReconciliationInterval` via a config property. It would be useful to allow an installer to override this at runtime when the value given in `@ControllerConfiguration` isn't suitable for a particular environment.

**Comment by metacosm** [comment]
Indeed, this isn't currently possible. Will implement this.

**Comment by metacosm** [comment]
See linked PR. Let me know if this works out for you.
