### ISSUE TITLE
Allow Bundle CSV annotations to be given via configuration

### ISSUE THREAD

**Issue by MikeEdgar** [quarkiverse/quarkus-operator-sdk#903]
We can currently add annotations to the CSV using `@CSVMetadata`, but some annotations are dynamic and would be better given via configs.

For example:
- `olm.skipRange`
- `createdAt`
- `containerImage` (bundle generator could probably optionally figure this one out automatically)

Maybe a general purpose solution could be to allow configuration of arbitrary annotations via config like:
```
quarkus.operator-sdk.bundle.annotations."my-annotation"=annotation-value
```

**Comment by metacosm** [comment]
Let me know if #947 addresses your issue.
