### ISSUE TITLE
Cluster level resources have namespace incorrectly applied

### ISSUE THREAD

**Issue by nstuart-idexx** [quarkiverse/quarkus-operator-sdk#964]
When the ClusterRole, ClusterRoleBinding resources are generated with the project property of `quarkus.kubernetes.namespace` set, the namespace gets applied to this resources, even though they are not supported. `kubectl apply` doesn't seem to care, but if we try to run these items through Terraform, with the latest kubernetes provider it runs extra validation and wont let these items be created;

```
│ Error: Cluster level resource cannot take namespace
│ 
│   with kubernetes_manifest.operator["ClusterRole--josdk-crd-validating-cluster-role"],
│   on main.tf line 39, in resource "kubernetes_manifest" "operator":
│   39: resource "kubernetes_manifest" "operator" {
│ 
│ Resources of type 'rbac.authorization.k8s.io/v1, Kind=ClusterRole' cannot
│ have a namespace
```

While `apply` works, it still seems to be incorrect to set the namespace on these resources and could likely cause confusion for folks who are troubleshooting their operators.

**Comment by nstuart-idexx** [comment]
For anyone else running into this in the future, I worked around the issue in Terraform with the following:

```
locals{
  correctedResources = [
    for resource in local.resources : merge(resource,
      { metadata = merge(resource.metadata, { namespace = startswith(resource.kind, "Cluster") ? null : resource.metadata.namespace }) })
  ]
}

locals {
  resources     = provider::kubernetes::manifest_decode_multi(file("kubernetes.yml"))
}
```

**Comment by metacosm** [comment]
Which version of Quarkus and the QOSDK are you using? There used to be an issue in Quarkus where using `quarkus.kubernetes.namespace` was putting namespace on clustered resource but I thought that got fixed a while ago…

**Comment by nstuart-idexx** [comment]
Slightly out of date, but not that old. 
```
quarkusPluginId=io.quarkus
quarkusPluginVersion=3.12.2
quarkusPlatformGroupId=io.quarkus.platform
quarkusPlatformArtifactId=quarkus-bom
quarkusPlatformVersion=3.12.2
```

I'll try updating, but I believe I tried previously ran into some issues with the latest version and some other dependencies. Will report back.

**Comment by nstuart-idexx** [comment]
Ok, thanks! Would you like me to open the issue? I'm not sure what project file it under, still new to the Quarkiverse architecture and layout. If you point me to a spot, happy to file it and close this out.

**Comment by nstuart-idexx** [comment]
Thanks for looking at this, and see the issue...missed that while writing my previous reply. Will close this out for now.
